insert into staff values('s01', '张三', 25);
insert into staff values('s02', '春天里asdglkj', 23);
insert into staff values('s03', '刘三', 26);
insert into staff values('s04', '万里高空', 28);
insert into staff values('s05', '张武', 28);
insert into staff values('s06', 'xiaopang', 26);
insert into staff values('s07', '海贼王', 26);
insert into staff values('s08', '王者荣耀', 26);
insert into staff values('s09', '张天', 26);